name: avi_music
description: Avi Music for Windows - ad-free music player.
publish_to: none
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  media_kit: ^1.1.10
  media_kit_libs_windows_audio: ^1.0.9
  smtc_windows: ^1.0.0
  window_manager: ^0.4.2

flutter:
  uses-material-design: true
